
import React from 'react';
import { Wrench, Shield, Zap, Award, Clock, ThumbsUp } from 'lucide-react';

export const MAPS_URL = "https://maps.app.goo.gl/o5GcgVips4DgsTYf8?g_st=aw";

export const TRANSLATIONS = {
  ar: {
    navHome: 'الرئيسية',
    navServices: 'خدماتنا',
    navBook: 'حجز موعد',
    navTrack: 'تتبع السيارة',
    navContact: 'اتصل بنا',
    navAdmin: 'لوحة التحكم',
    heroTitle: 'مركز أبو المجد الهندسي',
    heroSubtitle: 'وجهتكم المعتمدة في مدينة عطبرة لصيانة السيارات الحديثة. نجمع بين الخبرة الهندسية وأحدث تقنيات التشخيص لضمان أداء سيارتكم.',
    btnBookNow: 'احجز موعدك الآن',
    btnTrackCar: 'تتبع حالة سيارتك',
    servicesTitle: 'حلول هندسية متكاملة',
    bookingTitle: 'حجز موعد صيانة',
    bookingSubtitle: 'نظام الحجز المسبق يضمن لك الخدمة الأسرع والأكثر دقة في مركزنا بعطبرة',
    trackingTitle: 'تتبع صيانة سيارتك',
    trackingSubtitle: 'نظام شفاف يتيح لك متابعة كل خطوة في عملية الصيانة لحظة بلحظة',
    trackingPlaceholder: 'أدخل رقم الحجز (مثلاً: ABU-123)',
    btnCheckStatus: 'عرض حالة السيارة',
    formName: 'الاسم بالكامل',
    formPhone: 'رقم الهاتف',
    formCar: 'نوع وموديل السيارة',
    formPlate: 'رقم لوحة المركبة',
    formService: 'القسم المطلوب',
    formDate: 'التاريخ والوقت المفضل',
    btnConfirmBooking: 'تأكيد طلب الحجز',
    bookingSuccess: 'تم استلام طلبك بنجاح! فريقنا سيتصل بك قريباً لتأكيد الموعد.',
    adminTitle: 'إدارة العمليات',
    adminSubtitle: 'مراقبة وتحديث سير العمل في الأقسام المختلفة',
    adminName: 'العميل',
    adminStatus: 'المرحلة الحالية',
    adminActions: 'إدارة',
    adminUpdate: 'تحديث الحالة',
    adminSave: 'حفظ التعديل',
    adminLogout: 'تسجيل الخروج',
    loginTitle: 'دخول الموظفين',
    loginSubtitle: 'الوصول آمن للمخولين فقط',
    loginUser: 'اسم المستخدم',
    loginPass: 'كلمة المرور',
    btnLogin: 'تسجيل الدخول',
    loginError: 'عذراً، بيانات الدخول غير صحيحة',
    noBookingFound: 'لم نتمكن من العثور على حجز بهذا الرقم. يرجى التأكد من الرمز.',
    copyright: '© 2024 مركز أبو المجد الهندسي - عطبرة. جميع الحقوق محفوظة.',
    langName: 'English',
    status_0: 'تم استلام السيارة',
    status_1: 'الفحص والتشخيص الهندسي',
    status_2: 'أعمال السمكرة وهيكل السيارة',
    status_3: 'الدهان والطلاء الحراري',
    status_4: 'الصيانة الميكانيكية والكهربائية',
    status_5: 'ضبط الجودة واللمسات النهائية',
    status_6: 'السيارة جاهزة للتسليم',
    adminSettingsTitle: 'إعدادات النظام',
    scheduleControl: 'إدارة الجدول الزمني',
    dayStatusAvailable: 'متاح',
    dayStatusBusy: 'مزدحم',
    dayStatusClosed: 'مغلق',
    bookingClosedMsg: 'عذراً، الحجوزات متوقفة لهذا اليوم.',
    bookingBusyMsg: 'تنبيه: المركز مزدحم حالياً، قد يتأخر موعد الاستلام.',
    fullAddress: 'السودان، ولاية نهر النيل - عطبرة، المنطقة الصناعية الجديدة، شمال إدارة الجمارك',
    aiAssistantTitle: 'مساعد أبو المجد الذكي',
    aiAssistantSubtitle: 'تحدث مع خبيرنا الاصطناعي حول أعطال سيارتك أو خدماتنا',
    aiPlaceholder: 'كيف يمكننا مساعدتك اليوم؟',
    aiSystemPrompt: 'أنت مساعد مهندس ذكي في "مركز أبو المجد الهندسي" بمدينة عطبرة، السودان. تخصصك هو تقديم نصائح تقنية حول صيانة السيارات (ميكانيكا، سمكرة، دهان، فحص إلكتروني). رد بروح سودانية مهذبة ومهنية. شجع العملاء على الحجز إذا كان العطل يحتاج فحصاً. نحن نقع في المنطقة الصناعية الجديدة شمال الجمارك. رقم هاتفنا الأساسي هو 0124255855.',
    featuresTitle: 'لماذا يثق بنا العملاء؟',
    feature1Title: 'كادر هندسي متخصص',
    feature1Desc: 'نعتمد على مهندسين وفنيين ذوي خبرة طويلة في صيانة أعقد أنظمة السيارات.',
    feature2Title: 'التزام تام بالزمن',
    feature2Desc: 'نقدر وقتكم، لذا نلتزم بتسليم السيارة في الموعد المتفق عليه دون تهاون في الجودة.',
    feature3Title: 'شفافية ومصداقية',
    feature3Desc: 'نطلع العميل على كافة التفاصيل وقطع الغيار المستبدلة بشفافية مطلقة.',
    stats1: 'مركبة تمت صيانتها',
    stats2: 'تقييم رضا العملاء',
    stats3: 'مهندس وفني مختص',
    processTitle: 'دورة الصيانة لدينا',
    step1: 'فحص كمبيوتر وتفتيش',
    step2: 'خطة عمل وتنفيذ',
    step3: 'اختبار الطريق والجودة',
    step4: 'تسليم آمن ونظيف'
  },
  en: {
    navHome: 'Home',
    navServices: 'Services',
    navBook: 'Booking',
    navTrack: 'Tracking',
    navContact: 'Contact',
    navAdmin: 'Admin',
    heroTitle: 'Abu-Almagd Engineering Center',
    heroSubtitle: 'Your certified destination in Atbara for modern car maintenance. We combine engineering expertise with the latest diagnostics to ensure peak performance.',
    btnBookNow: 'Book Appointment',
    btnTrackCar: 'Track Your Car',
    servicesTitle: 'Integrated Engineering Solutions',
    bookingTitle: 'Service Booking',
    bookingSubtitle: 'Our pre-booking system ensures the fastest and most precise service at our Atbara center.',
    trackingTitle: 'Track Your Vehicle',
    trackingSubtitle: 'A transparent system allowing you to monitor every stage of maintenance in real-time.',
    trackingPlaceholder: 'Enter Booking ID (e.g., ABU-123)',
    btnCheckStatus: 'Check Progress',
    formName: 'Full Name',
    formPhone: 'Phone Number',
    formCar: 'Car Make & Model',
    formPlate: 'License Plate',
    formService: 'Required Department',
    formDate: 'Preferred Date & Time',
    btnConfirmBooking: 'Confirm Booking Request',
    bookingSuccess: 'Request received! Our team will contact you shortly to confirm your slot.',
    adminTitle: 'Operations Management',
    adminSubtitle: 'Monitor and update workflow across departments',
    adminName: 'Customer',
    adminStatus: 'Current Phase',
    adminActions: 'Manage',
    adminUpdate: 'Update Status',
    adminSave: 'Save Changes',
    adminLogout: 'Logout',
    loginTitle: 'Staff Portal',
    loginSubtitle: 'Secure access for authorized personnel only',
    loginUser: 'Username',
    loginPass: 'Password',
    btnLogin: 'Login',
    loginError: 'Incorrect credentials provided.',
    noBookingFound: 'No booking found with this ID. Please check the code.',
    copyright: '© 2024 Abu-Almagd Center - Atbara. All rights reserved.',
    langName: 'العربية',
    status_0: 'Vehicle Received',
    status_1: 'Engineering Inspection',
    status_2: 'Bodywork & Chassis',
    status_3: 'Thermal Paint & Coating',
    status_4: 'Mechanical & Electrical',
    status_5: 'Quality Control',
    status_6: 'Ready for Collection',
    adminSettingsTitle: 'System Settings',
    scheduleControl: 'Schedule Management',
    dayStatusAvailable: 'Available',
    dayStatusBusy: 'Busy',
    dayStatusClosed: 'Closed',
    bookingClosedMsg: 'Sorry, bookings are closed for today.',
    bookingBusyMsg: 'Notice: Center is currently busy; delivery might be slightly delayed.',
    fullAddress: 'Sudan, River Nile State - Atbara, New Industrial Area, North of Customs Administration',
    aiAssistantTitle: 'Abu-Almagd AI Helper',
    aiAssistantSubtitle: 'Discuss car issues or services with our intelligent expert',
    aiPlaceholder: 'How can we help you today?',
    aiSystemPrompt: 'You are an intelligent engineering assistant at "Abu-Almagd Engineering Center" in Atbara, Sudan. You specialize in vehicle maintenance technical advice (mechanics, bodywork, paint, electronics). Reply with a professional and helpful tone. Encourage booking if an inspection is needed. We are located in the New Industrial Area north of Customs. Primary phone: 0124255855.',
    featuresTitle: 'Why Do Customers Trust Us?',
    feature1Title: 'Expert Engineering Staff',
    feature1Desc: 'We rely on engineers and technicians with long experience in maintaining complex car systems.',
    feature2Title: 'Strict Punctuality',
    feature2Desc: 'We value your time, committing to deliver your car on schedule without compromising quality.',
    feature3Title: 'Integrity & Transparency',
    feature3Desc: 'We provide customers with all details and parts replaced with absolute transparency.',
    stats1: 'Vehicles Repaired',
    stats2: 'Customer Satisfaction',
    stats3: 'Expert Engineers',
    processTitle: 'Our Maintenance Lifecycle',
    step1: 'Scan & Inspection',
    step2: 'Execution & Planning',
    step3: 'Road Test & QC',
    step4: 'Safe Delivery'
  }
};

export const SERVICES = [
  {
    id: 'mech',
    titleAr: 'صيانة ميكانيكية متقدمة',
    titleEn: 'Advanced Mechanics',
    descAr: 'تشمل المحركات، نواقل الحركة، وأنظمة التعليق باستخدام أدوات دقيقة.',
    descEn: 'Including engines, transmissions, and suspension systems using precision tools.',
    icon: <Wrench className="w-12 h-12 text-[#ff9900]" />
  },
  {
    id: 'paint',
    titleAr: 'السمكرة والدهان الحراري',
    titleEn: 'Body & Thermal Paint',
    descAr: 'إصلاح الهيكل بأحدث تقنيات السمكرة ودهان بفرن حراري يضمن لمعان الوكالة.',
    descEn: 'Chassis repair with modern bodywork and thermal oven painting for factory-finish gloss.',
    icon: <Shield className="w-12 h-12 text-[#ff9900]" />
  },
  {
    id: 'elec',
    titleAr: 'الفحص الإلكتروني والبرمجة',
    titleEn: 'Diagnostics & Coding',
    descAr: 'كشف دقيق للأعطال ببرمجيات حديثة تشمل كافة الحساسات وكمبيوتر السيارة.',
    descEn: 'Precise fault detection with modern software covering all sensors and ECUs.',
    icon: <Zap className="w-12 h-12 text-[#ff9900]" />
  }
];

export const FEATURES = [
  {
    id: 'f1',
    icon: <Award className="w-10 h-10 text-[#ff9900]" />,
    titleAr: TRANSLATIONS.ar.feature1Title,
    titleEn: TRANSLATIONS.en.feature1Title,
    descAr: TRANSLATIONS.ar.feature1Desc,
    descEn: TRANSLATIONS.en.feature1Desc,
  },
  {
    id: 'f2',
    icon: <Clock className="w-10 h-10 text-[#ff9900]" />,
    titleAr: TRANSLATIONS.ar.feature2Title,
    titleEn: TRANSLATIONS.en.feature2Title,
    descAr: TRANSLATIONS.ar.feature2Desc,
    descEn: TRANSLATIONS.en.feature2Desc,
  },
  {
    id: 'f3',
    icon: <ThumbsUp className="w-10 h-10 text-[#ff9900]" />,
    titleAr: TRANSLATIONS.ar.feature3Title,
    titleEn: TRANSLATIONS.en.feature3Title,
    descAr: TRANSLATIONS.ar.feature3Desc,
    descEn: TRANSLATIONS.en.feature3Desc,
  }
];

export const getTrackingSteps = (lang: 'ar' | 'en') => [
  lang === 'ar' ? TRANSLATIONS.ar.status_0 : TRANSLATIONS.en.status_0,
  lang === 'ar' ? TRANSLATIONS.ar.status_1 : TRANSLATIONS.en.status_1,
  lang === 'ar' ? TRANSLATIONS.ar.status_2 : TRANSLATIONS.en.status_2,
  lang === 'ar' ? TRANSLATIONS.ar.status_3 : TRANSLATIONS.en.status_3,
  lang === 'ar' ? TRANSLATIONS.ar.status_4 : TRANSLATIONS.en.status_4,
  lang === 'ar' ? TRANSLATIONS.ar.status_5 : TRANSLATIONS.en.status_5,
  lang === 'ar' ? TRANSLATIONS.ar.status_6 : TRANSLATIONS.en.status_6
];
